name: CI
on:
  pull_request:
    branches: -main
  push:
    branches: -main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm test -- --ci

      - name: Prisma validate
        run: |
          npx prisma format
          npx prisma validate

      - name: Build
        run: npm run build
